project 'JALHomePage.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JALHomePage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JALHomePage
    # 第三方库
    pod 'MGJRouter'
end
